config/routes.rb
BandAdmin::Application.routes.draw do
  resources :proprietarios
  resources :locais
  resources :eventos
  resources :organizadors
  resources :repertorios
  resources :musicas
  resources :ordemmusicas

  get "pages/inicio"
  root :to => 'pages#inicio'
  mount Dinde::Engine => "/dinde"
end

app/models/evento.rb
class Evento < ActiveRecord::Base
  # attr_accessible :data, :nome, :local_id, :organizador_id, :repertorio_id
  belongs_to :local
  belongs_to :organizador
  belongs_to :repertorio

  def local
  	Local.find(local_id)
  end

  def organizador
  	Organizador.find(organizador_id)
  end

  def repertorio
  	Repertorio.find(repertorio_id)
  end
end

app/models/fonte.rb
# encoding: utf-8

class Fonte < ActiveRecord::Base
  # attr_accessible :corrente, :nome , :comprimento, :largura, :saidas
  has_many :saidas, class_name: 'SaidaFonte'
  belongs_to :mala
  

  def dimensoes
    [largura , comprimento]
  end

  def largura_util
  	largura + 10
  end

  def comprimento_util
  	comprimento + 20
  end

  def area
  	largura_util * comprimento_util
  end

  def adicionar_saida(saida)
    if saidas.count >= 5
      unless @especificacoes
        raise "Definir Especificações da fonte"
      else
        if saidas_usadas[saida.tensao] < @especificacoes[saida.tensao]
          saidas << saida
        else
          raise "Não disponível saídas de #{saida.tensao}v"
        end
      end
    else
      saidas << saida
    end
  end

  def corrente_disponivel
    corrente - corrente_total
  end

  def corrente_total
    if saidas.empty?
      0
    else
      saidas.map(&:corrente_pedal).reduce(:+)
    end
  end

  def pedais
    saidas.map(&:pedal)
  end

  def saidas_usadas
    lista =  {}
    if saidas.empty?
      lista
    else
      saidas.map(&:tensao).uniq.each do |s|
        lista[s] = saidas.map(&:tensao).count(s)
      end
    end
    lista
  end

  def especificacoes=(definicao)
    @especificacoes = definicao
  end

  def especificacoes
    @especificacoes
  end

  def especificacoes_humanizado
    if @especificacoes
      humanizar @especificacoes
    else
      humanizar saidas_usadas
    end
  end

  def humanizar(hash)
    string = ""
    lista = []
    hash.each do |chave, valor|
      lista << ("#{valor} saida#{valor > 1 ? 's' : ''} de #{chave}v")
    end
    lista.to_sentence.gsub(/\,? and /, ' e ')
  end

end

app/models/local.rb
class Local < ActiveRecord::Base
  # attr_accessible :cidade, :endereco, :nome, :tipo, :proprietario_id
  belongs_to :proprietario
  has_many :eventos

  def proprietario
  	Proprietario.find(proprietario_id)
  end
end

app/models/mala.rb
# encoding: utf-8

class Mala < ActiveRecord::Base
  # attr_accessible :comprimento, :largura, :nome, :pedais, :fontes
  has_many :pedais
  has_many :fontes

  def dimensoes
    [largura, comprimento]
  end

  def adicionar_pedal(pedal)
    if pedal.area <= area
      pedais << pedal
    else
      raise "Mala não possue espaço para #{pedal.nome}"
    end
  end

  def corrente_total
    unless pedais.empty?
      pedais.map(&:corrente).reduce(:+)
    end
  end

  def area
    area = largura * comprimento
    if equipamentos.empty?
      area
    else
      area - equipamentos.map(&:area).reduce(:+)
    end
  end

  def adicionar_fonte(fonte)
    if fonte.area <= area
      fontes << fonte
    else
      raise "Mala não possue espaço para #{fonte.nome}"
    end
  end

  def equipamentos
    pedais + fontes
  end

  def redimensionar(largura, comprimento)
    self.largura = largura
    self.comprimento = comprimento
  end

  def lista_equipamentos
    lista = {}
    unless fontes.empty?
      lista['Fonte'] = fontes.map{|p| [p.nome , 
                      {'Especificações'=>p.especificacoes_humanizado+ 
                        ". Corrente total: #{p.corrente}mA"}]}
    end
    unless pedais.empty?
      pedais.map(&:tipo).uniq.each do |tipo|
        lista[tipo] = pedais.where(:tipo => tipo).map(&:nome)
      end
    end
    lista
  end
  
  private 
  def largura_livre
    if pedais.empty?
      largura
    else
      largura_pedais = pedais.map(&:largura_util).reduce(:+)
      largura - largura_pedais
    end
  end
end

app/models/musica.rb
class Musica < ActiveRecord::Base
  # attr_accessible :bpm, :duracao, :estilo, :nome
  has_many :ordemmusicas
  has_many :repertorios, :through => :ordemmusicas
end

app/models/ordemmusica.rb
class Ordemmusica < ActiveRecord::Base
  # attr_accessible :musica_id, :ordem, :repertorio_id
  belongs_to :musicas
  belongs_to :repertorios

  def musica
    Musica.find(musica_id)
  end

  def repertorio
    Repertorio.find(repertorio_id)
  end
end

app/models/organizador.rb
class Organizador < ActiveRecord::Base
  # attr_accessible :contato, :nome
  has_many :eventos
end

app/models/pedal.rb
class Pedal < ActiveRecord::Base
  # attr_accessible :comprimento, :corrente, :largura, :nome, :tensao, :tipo, :mala, :saida_fonte
  belongs_to :mala
  has_one :saida_fonte

  def dimensoes
  	[largura, comprimento]
  end

  def area
  	largura_util * comprimento_util
  end

  def largura_util
  	largura + 20
  end

  def comprimento_util
  	comprimento + 10
  end
end

app/models/proprietario.rb
class Proprietario < ActiveRecord::Base
  # attr_accessible :contato, :nome
  has_many :locais
end

app/models/repertorio.rb
class Repertorio < ActiveRecord::Base
  # attr_accessible :nome
  has_many :ordemmusicas
  has_many :musicas, :through => :ordemmusicas
  has_many :eventos
end

app/models/saida_fonte.rb
# encoding: utf-8

class SaidaFonte < ActiveRecord::Base
  # attr_accessible :centro_negativo, :tensao, :fonte, :pedal
  belongs_to :fonte
  belongs_to :pedal
  
  def conectar(pedal)
    if pedal.corrente >= fonte.corrente_disponivel
      raise "Corrente do pedal superior ao disponível"
    elsif pedal.tensao != tensao
      raise "Tensao do pedal superior ao da saida"
    else
      self.pedal = pedal
    end
  end

  def corrente_pedal
    pedal.try(:corrente) || 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/evenos_controller.rb
class EventosController < InheritedResources::Base
end

app/controllers/eventos_controller.rb
class EventosController < InheritedResources::Base
end

app/controllers/locais_controller.rb
class LocaisController < InheritedResources::Base
end

app/controllers/musicas_controller.rb
class MusicasController < InheritedResources::Base
end

app/controllers/ordemmusicas_controller.rb
class OrdemmusicasController < InheritedResources::Base
end

app/controllers/organizadors_controller.rb
class OrganizadorsController < InheritedResources::Base
end

app/controllers/pages_controller.rb
# encoding: utf-8
class PagesController < ApplicationController
  def inicio
    @title = "Página Inicial"
  end
end

app/controllers/repertorios_controller.rb
class RepertoriosController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "Band Admin"
    if @title.nil?
      base_title
    else
      "#{@title} | #{base_title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/eventos/_form.html.haml
= semantic_form_for (@evento) do |form|
  = form.input :nome, :label => 'Nome'
  = form.input :data, :label => 'Data'
  = form.input :local_id, as: :select, collection: Local.all.map { |local| [local.nome, local.id] }, prompt: false, :label => "Local"
  = form.input :organizador_id, as: :select, collection: Organizador.all.map { |organizador| [organizador.nome, organizador.id] }, prompt: false, :label => "Organizador"
  = form.input :repertorio_id, as: :select, collection: Repertorio.all.map { |repertorio| [repertorio.nome, repertorio.id] }, prompt: false, :label => "Repertório"
  = form.submit 'Salvar'

app/views/eventos/edit.html.haml
%h2 Editar Evento

= render 'form'

= link_to 'Show', @evento
= link_to 'Voltar', eventos_path

app/views/eventos/index.html.haml
%h1 Gerenciador de Eventos
%table
	%tr
		%th Nome
		%th Data
		%th Local
		%th Organizador
		%th Repertório
		-@eventos.each do |evento|
			%tr
				%td= evento.nome
				%td= evento.data
				%td= evento.local.nome
				%td= evento.organizador.nome
				%td= evento.repertorio.nome
				
				%td= link_to 'Show', evento
				%td= link_to 'Editar', edit_evento_path(evento)
				%td= link_to 'Excluir', evento, method: :delete, data: {confirm: "Tem certeza que irá deletar #{evento.nome}?"}
= link_to 'Adicionar Evento', new_evento_path

app/views/eventos/new.html.haml
%h2 Adicionar Evento

= render 'form'

app/views/eventos/show.html.haml
%p#notice= notice
%p
  %b Nome:
  = @evento.nome
%p
  %b Data:
  = @evento.data
%p
  %b Local:
  = @evento.local.nome
%p
  %b Organizador:
  = @evento.organizador.nome
%p
  %b Repertório:
  = @evento.repertorio.nome

= link_to 'Editar', edit_evento_path(@evento)
= link_to 'Voltar', eventos_path

app/views/musicas/_form.html.haml
= semantic_form_for [@musica] do |form|
  = form.input :nome, :label => 'Nome'
  = form.input :duracao, :label => 'Duração'
  = form.input :bpm, :label => 'bpm'
  = form.input :estilo, :label => 'Estilo'
  = form.submit 'Salvar'

app/views/musicas/edit.html.haml
%h2 Editar Música

= render 'form'

= link_to 'Show', @musica
= link_to 'Voltar', musicas_path

app/views/musicas/index.html.haml
%h1 Gerenciador de Músicas
%table
  %tr
    %th Nome
    %th Duração
    %th bpm
    %th Estilo
    -@musicas.each do |musica|
      %tr
        %td= musica.nome
        %td= musica.duracao
        %td= musica.bpm
        %td= musica.estilo
        %td= link_to 'Show', musica
        %td= link_to 'Editar', edit_musica_path(musica)
        %td= link_to 'Excluir', musica, method: :delete, data: { confirm: "Tem certeza que irá deletar #{musica.nome}?"}
%br
= link_to 'Adicionar Músicas', new_musica_path

app/views/musicas/new.html.haml
%h2 Adicionar Música

= render 'form'

app/views/musicas/show.html.haml
%p#notice= notice
%p
  %b Nome:
  = @musica.nome
%p
  %b Duração:
  = @musica.duracao
%p
  %b bpm:
  = @musica.bpm
%p
  %b Estilo:
  = @musica.estilo
= link_to 'Editar', edit_musica_path(@musica)
  
= link_to 'Voltar', musicas_path

app/views/ordemmusicas/_form.html.haml
= semantic_form_for [@ordemmusica] do |form|
  = form.input :ordem, :label => 'Ordem'
  = form.input :musica_id, as: :select, collection: Musica.all.map { |musica| [musica.nome, musica.id] }, prompt: false, :label => "Música"
  = form.input :repertorio_id, as: :select, collection: Repertorio.all.map { |repertorio| [repertorio.nome, repertorio.id] } , :label => "Repertório"

  = form.submit 'Salvar'

app/views/ordemmusicas/edit.html.haml
%h2 Editar Ordem das Músicas

= render 'form'

= link_to 'Show', @ordemmusica
= link_to 'Voltar', ordemmusicas_path

app/views/ordemmusicas/index.html.haml
%h1 Gerenciador de Ordem das Músicass
%table
  %tr
    %th Ordem
    %th Música
    %th Repertório
    -@ordemmusicas.each do |ordemmusica|
      %tr
        %td= ordemmusica.ordem
        %td= ordemmusica.musica.nome
        %td= ordemmusica.repertorio.nome
        %td= link_to 'Show', ordemmusica
        %td= link_to 'Editar', edit_ordemmusica_path(ordemmusica)
        %td= link_to 'Excluir', ordemmusica, method: :delete, data: { confirm: "Tem certeza que irá deletar?"}
%br
= link_to 'Adicionar Ordem à Música', new_ordemmusica_path

app/views/ordemmusicas/new.html.haml
%h2 Adicionar Ordem à Música

= render 'form'

app/views/ordemmusicas/show.html.haml
%p#notice= notice
%p
  %b Ordem:
  = @ordemmusica.ordem
%p
  %b Música:
  = @ordemmusica.musica.nome
%p
  %b Repertório:
  = @ordemmusica.repertorio.nome

= link_to 'Editar', edit_ordemmusica_path(@ordemmusica)
  
= link_to 'Voltar', ordemmusicas_path

app/views/organizadors/_form.html.haml
= semantic_form_for [@organizador] do |form|
  = form.input :nome, :label => 'Nome'
  = form.input :contato, :label => 'Contato' 
  = form.submit 'Salvar'

app/views/organizadors/edit.html.haml
%h2 Editar Organizador

= render 'form'

= link_to 'Show', @organizador
= link_to 'Voltar', organizadors_path

app/views/organizadors/index.html.haml
%h1 Gerenciador de Organizadores
%table
  %tr
    %th Nome
    %th Contato
    -@organizadors.each do |organizador|
      %tr
        %td= organizador.nome
        %td= organizador.contato
        %td= link_to 'Show', organizador
        %td= link_to 'Editar', edit_organizador_path(organizador)
        %td= link_to 'Excluir', organizador, method: :delete, data: { confirm: "Tem certeza que irá deletar #{organizador.nome}?"}
%br
= link_to 'Adicionar Proprietário', new_organizador_path

app/views/organizadors/new.html.haml
%h2 Adicionar Organizador

= render 'form'

app/views/organizadors/show.html.haml
%p#notice= notice
%p
  %b Nome:
  = @organizador.nome
%p
  %b Contato:
  = @organizador.contato

= link_to 'Editar', edit_organizador_path(@organizador)
  
= link_to 'Voltar', organizadors_path

app/views/repertorios/_form.html.haml
= semantic_form_for [@repertorio] do |form|
  = form.input :nome, :label => 'Nome'
  = form.submit 'Salvar'

app/views/repertorios/edit.html.haml
%h2 Editar Repertório

= render 'form'

= link_to 'Show', @repertorio
= link_to 'Voltar', repertorios_path

app/views/repertorios/index.html.haml
%h1 Gerenciador de Repertórios
%table
  %tr
    %th Nome
    -@repertorios.each do |repertorio|
      %tr
        %td= repertorio.nome
        %td= link_to 'Show', repertorio
        %td= link_to 'Editar', edit_repertorio_path(repertorio)
        %td= link_to 'Excluir', repertorio, method: :delete, data: { confirm: "Tem certeza que irá deletar #{repertorio.nome}?"}
%br
= link_to 'Adicionar Repertório', new_repertorio_path

app/views/repertorios/new.html.haml
%h2 Adicionar Repertório

= render 'form'

app/views/repertorios/show.html.haml
%p#notice= notice
%p
  %b Nome:
  = @repertorio.nome

= link_to 'Editar', edit_repertorio_path(@repertorio)
  
= link_to 'Voltar', repertorios_path